### ISSUE TITLE
Dark and light mode

### ISSUE THREAD

**Issue by dmxt** [libhide/simplebox.js#2]
This is a suggestion to add dark/light mode to setting to make background either white or black.

**Comment by RayPS** [comment]
+1 for this
And i think it's better if we make the css and svg files to a single min.js file.

**Comment by libhide** [comment]
Interesting. I'm surely going to look into this as soon as possible!

**Comment by libhide** [comment]
Hey @RayPS! Have a look at 7a50140. I've removed the SVG dependency. 
How do you suggest I go about reducing the plugin to just a min.js file? CSS within the JS?
