### ISSUE TITLE
Doesn't include srcset attribute

### ISSUE THREAD

**Issue by elkcl** [libhide/simplebox.js#8]
I have 2 variants of an image: 1x and 2x. I want to display the 1x on the page and 2x in the simplebox pop-up. I tried using srcset, but simplebox doesn't transfer it to the pop-up image. It would be very nice if simplebox could use the high-resolution image instead of just the one on the page.

**Comment by libhide** [comment]
Good idea – might try to build this out over a weekend soon! Although, if you want to try to build it and  submit a PR, that would be great too!
